name: Test PyCIFRW

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

  workflow_dispatch:
  
jobs:
        test:
                runs-on: ubuntu-latest

                strategy:
                        matrix:
                                python-version: ['3.10']
                                os: [ubuntu-latest] #, macos13, macos-latest, windows-2022, windows-latest]
                steps:
                - name: Checkout code
                  uses: actions/checkout@v4

                - name: Set up Python ${{ matrix.python-version }}
                  uses: actions/setup-python@v5
                  with:
                          python-version: ${{ matrix.python-version }}

                - name: Create derived files
                  run: |
                       cd src; make
                       
                - name: Install dependencies
                  run: |
                          python -m pip install --upgrade pip
                          pip install pytest
                          pip install .

                - name: Check installed contents
                  run: |
                        PKG_PATH=$(python -c "import site, os; print([p for p in site.getsitepackages() if os.path.exists(os.path.join(p, 'CifFile'))][0])")
                        ls -la $PKG_PATH/CifFile

                - name: Get cif core dictionary for tests
                  uses: actions/checkout@v4
                  with:
                     repository: COMCIFS/cif_core
                     path: tests/drel
                     sparse-checkout: |
                             cif_core.dic
                             templ_enum.cif
                             templ_attr.cif

                - name: Run tests
                  run: |
                          pytest TestPyCIFRW.py
                          # pytest TestDrel.py
